### ISSUE TITLE
Update for OJS 3.3/3.4

### ISSUE THREAD

**Issue by Jannik-Lappe** [ojsde/vgWort#11]
Greetings,

Will there be an update for OJS 3.3/3.4?
Went to the Heidelberg-Fork but didn't find a way to ask there.

Best Regards
Jannik Lappe

**Comment by ronste** [comment]
Hi @Jannik-Lappe ,

you should contact [heiJournals](https://journals.ub.uni-heidelberg.de/) about further plugin development.

Best wishes,
Ronald
