### ISSUE TITLE
Option "allow_url_fopen" must be enabled in PHP.ini for the plugin to work

### ISSUE THREAD

**Issue by isgrim** [ojsde/vgWort#2]
Hi Bozana,

with some trial and error I found that this option has to be enabled in the PHP.ini for the plugin to work.
But it's not mentioned in the README or in the installation instructions.
Maybe it's also a good idea to add a check for this in the "requirementsFulfilled" Function.

Thanks for developing the plugin!

Wishing you a merry christmas,
Nils

**Comment by bozana** [comment]
I've implemented an additional solution using `CURL`, to check the VG Wort service and credentials, if `allow_url_fopen` in `php.ini` is not enabled. Thus, either `CURL` or `allow_url_fopen` has to exists.
PR: https://github.com/ojsde/vgWort/pull/3
