### ISSUE TITLE
White space in VGWortEditorHandler.inc.php

### ISSUE THREAD

**Issue by isgrim** [ojsde/vgWort#4]
Dear ojs-de Team,

there seems to be a small issue with a white space character in this file:
https://github.com/ojsde/vgWort/blob/ojs-stable-2_4_8/pages/VGWortEditorHandler.inc.php#L1
There exists a blank before the "<?php".

This prevents the file from being correctly included and corresponding pages like (editor/assignPixelTag) did not display in our case.

Maybe this is related to the question I found on StackOverflow: http://stackoverflow.com/questions/10199355/php-include-causes-white-space-at-the-top-of-the-page

Thanks and bye.

**Comment by bozana** [comment]
PR: https://github.com/ojsde/vgWort/pull/5
I hope this fixes the problem and that OJSde-Team will take a look at it...
