### ISSUE TITLE
Release for OJS 3

### ISSUE THREAD

**Issue by p-graeser** [ojsde/vgWort#6]
Dear ojs-de Team,

is there any plan to release a version of the vgWort plugin for OJS 3.0.X?

Best regards
Patrick Gräser

**Comment by isgrim** [comment]
Hi ojs-de Team,

I'm also interested in knowing if OJS 3 and newer will be supported in the future.

Cheers,
Nils Weiher

**Comment by lilients** [comment]
Hi @p-graeser and @isgrim,

thanks for the interest in this plugin! We have some capacities to do the migration of requested OJS 2 features to OJS 3. So this one is a good candidate. :)

Best,
Svantje Lilienthal

I will discuss this with my collegues.

**Comment by p-graeser** [comment]
Hi @lilients ,

can you give us a little status update?

Best regards,
Patrick Gräser
