### ISSUE TITLE
Automatisch registrieren über ScheduledTask funktioniert nicht 3.1.2-1

### ISSUE THREAD

**Issue by isgrim** [ojsde/vgWort#7]
Liebe Entwickler des OJS vgWort Plugins,

ich arbeite mit Daniela Wolf an der Betreuung der OJS Plattform der UB Heidelberg.

Leider kriege ich es nicht hin, die automatische Registrierung von VGWort Pixeln über die ScheduledTasks von OJS zu starten.

Wenn ich den Task mit diesem Befehl starte:
```
sudo -u www-data php tools/runScheduledTasks.php plugins/generic/vgWo│nw@pers42:~/dev/projects/omp-portals/web2py/applications/heiup/private$ als/web2py/applications/heiup
rt/scheduledTasks.xml
```
Bricht die Ausführung mit folgender Fehlerausgabe ab:
```
PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /web/htdocs-journals-3/plugins/generic/vgWort/classes/VGWortEditorAction.inc.php:250
Stack trace:
#0 /web/htdocs-journals-3/plugins/generic/vgWort/classes/VGWortEditorAction.inc.php(150): VGWortEditorAction->newMessage(Object(PixelTag), Object(Request))
#1 /web/htdocs-journals-3/plugins/generic/vgWort/VGWortInfoSender.inc.php(122): VGWortEditorAction->registerPixelTag(Object(PixelTag), Object(Request))
#2 /web/htdocs-journals-3/plugins/generic/vgWort/VGWortInfoSender.inc.php(91): VGWortInfoSender->_registerPixelTags(Object(DAOResultFactory))
#3 /web/htdocs-journals-3/lib/pkp/classes/scheduledTask/ScheduledTask.inc.php(148): VGWortInfoSender->executeActions()
#4 /web/htdocs-journals-3/lib/pkp/classes/cliTool/ScheduledTaskTool.inc.php(113): ScheduledTask->execute()
#5 /web/htdocs-journals-3/lib/pkp/classes/cliTool/ScheduledTaskTool.inc.php(95): ScheduledTaskTool->executeTask('plugins.generic...', Array)
#6 /web/htdocs-journals-3/lib/pkp/classes/cliToo in /web/htdocs-journals-3/plugins/generic/vgWort/classes/VGWortEditorAction.inc.php on line 250
```
Wenn man die Zeile in der VGWortEditorAction.inc.php Datei verfolgt.
Es sieht so aus als ob kein "Context" (journal) am Request Objekt vorliegt, weil es über die Konsole gestartet worden ist. Aber sollte es nicht möglich sein, die ScheduledTasks z.b. über CRON zu starten?

Können sie da helfen?

**Comment by ronste** [comment]
Hallo Isgrim,

der von dir angegebene Befehl zum Starten des Tasks scheint etwas durcheinander gekommen zu sein.

Ich sehe da Teile von verschiedenen Programmen und Ordnern die nicht zusammen und nicht zu vgWort passen: "omp-portals", "/applications/heiuprt/scheduledTasks.xml"

Könntest du bitte nochmal den genutzten Befehl posten? Du kannst uns auch direkt über e-Mail kontaktieren.

Grüße,
Ronald

**Comment by isgrim** [comment]
Hallo Rolan,

bitte entschuldige, da ist beim kopieren aus tmux etwas schief gegangen.
Hier die richtige Zeile, ausgeführt aus dem OJS Verzeichnis.
```
sudo -u www-data php tools/runScheduledTasks.php plugins/generic/vgWort/scheduledTasks.xml
```

**Comment by ronste** [comment]
Hallo Nils,

ich habe das gerade bei mir auf einer Einzelinstanz-Installation ausprobiert (OJS 3.1.2-3) und kriege keinen Fehler. Habt ihr eine Einzel- oder eine Multiinstanz-Installation?

Grüße,
Ronald

P.S: Bitte beachten, dass in dieser beta-Version nur die vgWort-Testserver aktiviert sind.

**Comment by isgrim** [comment]
Hm, es gibt mehrere Journals in der Instanz, also Multiinstanz.

**Comment by ronste** [comment]
Hallo Nils,

ich habe das jetzt nochmal auf einer Multiinstanz-Installation getestet. Auch hier habe ich keine Fehler bekommen.

Könntest du bitte nochmal git branches überprüfen? Also von OJS, lib/pkp und vgWort.

Grüße,
Ronald

**Comment by isgrim** [comment]
Hallo Roland,

siehst du in der Datenbank mit folgendem SQL befehl, ob das Script wirklich ausgeführt wurde:
"select * from ojs3.scheduled_tasks order by last_run"?

Weil wenn es einmal gestartet wurde am Tag, d.h. wenn es in dieser Tabelle eingetragen wurde wird der Task nicht mehr ausgeführt. Das Problem hatte ich am Anfang beim testen und habe dann "last_run" in der Tabelle auf NULL gesetzt.

**Comment by ronste** [comment]
Hallo Nils,

der Eintrag in "scheduled_tasks" ist bei mir vorhanden.

Aber nachdem ich ganz ganz tief im Code gegraben habe konnte ich deine Fehlermeldung dann doch noch reproduzieren. Ich habe einige Aktualisierungen im Code vorgenommen. Bitte "pulle" nochmal meinen Commit von heute und versuche es nochmal.

Danke für das Feedback!

Grüße,
Ronald

P.S. Ich bin dann bis zum 6. Juni im Urlaub

**Comment by isgrim** [comment]
Vielen Dank Ronald!!!
Ich probiere es gleich mal aus

**Comment by isgrim** [comment]
Liebe Ronald,

so hat es geklappt, also der Task ist gestartet und lief auch ohne Exception durch.
Allerdings wurden keine Pixel registriert. Ich bin dann auf diese Zeile gestoßen, nach dem ich mit Hilfe von error_log die Zeitstempel verglichen habe:
https://github.com/ojsde/vgWort/blob/ojs-stable-3_1_2-beta/VGWortInfoSender.inc.php#L83
Der erste Vergleich von `time()` mit `$checkDateInYear` klappt, für den einen Lauf ware das die ausgegebenen Werte:
```
time: 1590567384, checkDateInYear: 1590530400, lastRunShortDate: 1590530400
```
Beim zweiten Vergleich klappt es nicht, weil lastRunShortDate gleich checkDateInYear ist und damit nicht echt kleiner wie gefordert.

Das liegt wahrscheinlich auch daran, dass ich als Datum für die automatische Meldung das heutige (27.05.2020) eingetragen habe. Ich probiere es jetzt nochmal wenn ich ein in der Vergangenheit auswähle.

Meine Frage ist, wie das Verhalten von dem Task sein soll. Wenn der Task am gleichen Datum wie die Meldung gestartet wird, soll es dann auf jeden Fall gemeldet werden oder erst am nächsten Tag?

**Comment by ronste** [comment]
Ja, das Problem hatte ich gestern beim Testen auch. Zum Testen habe ich einfach 2 Tage zu time() hinzuaddiert. 
Diese Mechanik ist bei der ursprünglichen Programmierung wohl so vorgesehen worden. Keine Ahnung warum. Aber von mir aus können wir das Verhalten gerne anpassen. Ich bin für alle Vorschläge offen. Ich kann mich aber erst ab dem 8. Juni wieder darum kümmern.

**Comment by isgrim** [comment]
Okay kein Problem und viel Spaß im Urlaub!
Ich kann auch einen pull request öffnne mti einem Vorschlag und dann kannst du schauen, wenn du wieder zurück bist, ob es dir passt.

**Comment by ronste** [comment]
Bug behoben
